### ISSUE TITLE
Integrate api/job endpoint with Redux

### ISSUE THREAD

**Issue by charlesjavelona** [UnivJobs/univjobs-front#7]

**Comment by charlesjavelona** [comment]
Jotting down my thoughts here as I integrate react-redux with the backend.

**Comment by charlesjavelona** [comment]
<img width="1280" alt="screen shot 2016-10-02 at 7 56 53 pm" src="https://cloud.githubusercontent.com/assets/7959179/19024805/63e29538-88da-11e6-88bb-d5e2af6977c6.png">

**Comment by charlesjavelona** [comment]
**Update:**
 - Able to get jobs
<img width="1280" alt="screen shot 2016-10-10 at 11 07 00 pm" src="https://cloud.githubusercontent.com/assets/7959179/19268275/87e67cb2-8f81-11e6-8a62-c61d271e9471.png">

**Comment by charlesjavelona** [comment]
**TODO:**
 [] Make the modal work
 [] Pass the job attributes to the modal
 [] Enhance styling in the job modal 
 [] Move onto the backend to allow apply jobs
 [] Work on front-end code to apply to jobs as a student

**Comment by charlesjavelona** [comment]
**Notes on modal TODO(1):**
 [x]Pass the SkyLight and JobModalCard as children into the JobModal to test.
    Did not work, refs is still undefined. This is due to the component being a stateless component. A stateless component in default, unable to accept refs.

**There are a few of approaches I see to test out:**
 - Move all the components in the StudentDashboard container, an example would be [SignupLoginContainer](https://github.com/UnivJobs/univjobs-front/blob/dashboard/app/modules/SignupAndLogin/containers/SignupContainer.js).
 - At this moment is unclear, the gist of this other option is to use redux with the involvement of action creators and reducers.
 - Another would be, is to do a term called portal(need more research)

Heres is what I see so far, when the user clicks the button, an action could be dispatch to the store to send which job id is selected, the store then receives the job id, then somehow the modal opens with the appropriate job info. 

ACTION('Click button') => SEND(job_id, 'MODAL_CLICKED')=> Store('MODAL_CLICKED') => REDUCER('MODAL_OPEN=True') => Supply appropriate data

**Comment by charlesjavelona** [comment]
Finally got the modal working, please see this [commit](https://github.com/UnivJobs/univjobs-front/commit/aa048871d6fa0106d4b2b7c0db3bb3dfe5b46e9d) to understand what is going on.

Still need to refactor the code as Khalil mentioned only passed the need state.
See below video for inspiration.
http://courses.reactjsprogram.com/courses/redux-and-immutablejs/lectures/946368

**Comment by charlesjavelona** [comment]
Testing to see if it is possible to pass two objects on this endpoint at the same time. [endpoint](http://ec2-52-87-227-85.compute-1.amazonaws.com:8000/api/job/new/answer/)

**First test: Make it work**
  -  POST two objects in sequence.

**Second test: Testing one POST**
  -  With two objects inside a JSON array, POST the JSON array once .

**Comment by charlesjavelona** [comment]
Second test works. Now looking into making [backend issue #103](https://github.com/UnivJobs/univjobs-back/issues/103) work to complete the POST answer.

**Comment by charlesjavelona** [comment]
Successfully completed student answer.
A few things to refactor on the front-end code at this moment:

## TODO BEFORE REFACTOR:
  - [x] Make apply view work
  - [x] Make apply view work with answers
  - [x] Go to refactor section 



## TODO WHEN REFACTORING: 
- [x] Create a dispatch call for sending.
   - [x] Create a dispatch for success which empties the dispatch for the textboxes.
      - [x] After empty take the network response and show a toaster.
   - [x] Create a dispatch similar to success but with failure.
- [x] Create a dispatch for empty textboxes with toaster involved

**Comment by charlesjavelona** [comment]
Everything works. Need to do some error handling as well as minor tweaking. 
Some edge cases needs to be discussed with @stemmlerjs tomorrow.

**Comment by charlesjavelona** [comment]
Closed, https://github.com/UnivJobs/univjobs-front/commit/79cb740d646ce77c5a9db2d9063b5a24f60d7666
